### ISSUE TITLE
[BUG] Frozen Swordsmachine 0-3

### ISSUE THREAD

**Issue by EximpLettuce0** [eternalUnion/UltraPain#1]
# Description
On 0-3, if you have fought swordsmachine on the first arena on the level, he gets frozen on the second boss fight. This only happens when you have done his first phase prior in the level (if you go directly to the second bossfight, skipping the first one it doesn't happen).

# Reproduction
* Step 1: In 0-3, defeat Swordsmachine's in its first encounter.
* Step 2: Go to the second arena at the end of the level. Swordsmachine is frozen.

# Console logs
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SwordsMachine.SlowUpdate () (at <5129177de6a5457bbb0eef7a2402bf1b>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SwordsMachine.NavigationUpdate () (at <5129177de6a5457bbb0eef7a2402bf1b>:0)

# Extras
Attached a video that shows the bug.

https://github.com/eternalUnion/UltraPain/assets/120595794/8f6764c8-85b1-481e-bcf1-aa0a99bedd5e

**Comment by eternalUnion** [comment]
I failed to reproduce this bug, could you upload your config file and give me a list of any other plugins you could be using?

**Comment by eternalUnion** [comment]
Nevermind, it seems that it occurs when second phase is set to speed up.

**Comment by eternalUnion** [comment]
An experimental release has been produced to solve the bug https://github.com/eternalUnion/UltraPain/releases/tag/1.0.1

**Comment by eternalUnion** [comment]
Fixed on 1.0.1. Open if any further bugs occur.
