### ISSUE TITLE
Difficulty doesn't appear in the "BOOT UP SEQUENCE"

### ISSUE THREAD

**Issue by TheTurd125** [eternalUnion/UltraPain#10]
![ULTRAKILL 2023-05-15 18-27-50-69](https://github.com/eternalUnion/UltraPain/assets/79824410/b0b2f0c8-12f4-46f4-a1a8-9845223aaa68)

![ULTRAKILL 2023-05-15 18-29-05-86](https://github.com/eternalUnion/UltraPain/assets/79824410/251df0ed-ed01-4c9e-be25-fc2cfdb8453e)

**Comment by eternalUnion** [comment]
Should be fixed by version 1.0.2 https://github.com/eternalUnion/UltraPain/releases/tag/1.0.2
