### ISSUE TITLE
[FEATURE] Mindflayer immune to her own projectiles

### ISSUE THREAD

**Issue by EximpLettuce0** [eternalUnion/UltraPain#13]
# Feature
An option that makes the mindflayer immune to her own projectiles. Preferably similar to the friendly fire override in the global enemy tweaks, but exclusive to the mindflayer and the homing projectiles that she spawns.

# Usage
It is very easy to instakill midflayers with the knuckleblaster. This feature would make it so the player would decide whether or not they want that.

# Extras
Attached video showing the instakill with the KB.

https://github.com/eternalUnion/UltraPain/assets/120595794/c242c644-296d-4212-8489-a0be664a76fd

**Comment by eternalUnion** [comment]
Maybe a field to decrease the amount of damage taken (down to 0%) can be added. Also friendly fire is not what you reflect, but enemies hitting themselves (like streetcleaner burning enemies, not a parried projectile hitting an enemy), just in case you mixed them.

**Comment by eternalUnion** [comment]
Implemented on https://github.com/eternalUnion/UltraPain/releases/tag/fr13-1.0.2-0. Probably gonna use on the next update

**Comment by EximpLettuce0** [comment]
Closed because of implementation
