### ISSUE TITLE
[FEATURE] ChargeBacked-Orbital-Strike

### ISSUE THREAD

**Issue by MaximIce1** [eternalUnion/UltraPain#15]
# Feature
https://youtu.be/smgIBREyRjc

# Usage
defence from maurices \ turrets \ drones, but more stylish

# Extras
--

**Comment by eternalUnion** [comment]
This is a really good idea, but I need more information about what would happen on hit. I assume it would cause a malicious beam explosion, or beam splitting into multiple beams?

**Comment by MaximIce1** [comment]
maybe it can be big explosion from maurice's laser, and split laser if turret's shot

**Comment by eternalUnion** [comment]
Implemented first revision at https://github.com/eternalUnion/UltraPain/releases/tag/fr15-1.0.2-0
