### ISSUE TITLE
[BUG] Level ranking freeze

### ISSUE THREAD

**Issue by ThuursDay** [eternalUnion/UltraPain#17]
# Description
End of level ranking does not work. There is still sound, background of the elevator is moving, and you can quit the level. The next level becomes available, but the completed level has no ranking.

# Reproduction
* Step 1: Complete a level
That's it. Not sure if the installation is not correct or something.
Using the latest version of ultrakill and BepInEx 5.4.21, on Windows 11.

# Console logs

LogOutput.txt in BepInEx folder contents:

[Message:   BepInEx] BepInEx 5.4.21.0 - ULTRAKILL (27/04/2023 08:28:07)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [PluginConfigurator 1.3.1]
[Message:PluginConfigurator] cheatKeyPatch:true
[Message:PluginConfigurator] unpausePatch:true
[Message:PluginConfigurator] cancelOnEsc:true
[Message:PluginConfigurator] configTestToggle:false
[Message:PluginConfigurator] consoleLogLevel:Disabled
[Info   :PluginConfigurator] Working path: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\PluginConfigurator\PluginConfigurator.dll, Working dir: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\PluginConfigurator
[Info   :PluginConfigurator] Plugin com.eternalUnion.pluginConfigurator is loaded!
[Info   :   BepInEx] Loading [Ultra Pain 1.0.2]
[Info   :Ultra Pain] Working path: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\UltraPain\Ultrapain.dll, Working dir: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\UltraPain
[Info   :Ultra Pain] Plugin Ultrapain is loaded!
[Message:   BepInEx] Chainloader startup complete

# Extras

![image](https://github.com/eternalUnion/UltraPain/assets/37485169/e3f7843d-0b7e-444a-868a-dbdf4a92f15a)

**Comment by ThuursDay** [comment]
Solved by using another save!

Perhaps leaderboards or previous records affect it?

**Comment by eternalUnion** [comment]
This needs more investigation. The custom difficulty *should* use ultrakill must die slot. Will try to find the cause.

**Comment by eternalUnion** [comment]
Saw happen to another person. Seems some saves from older versions of ultrakill doesn't have the ukmd slot. Thus this bug happens when game tries to save to ukmd slot of the old save format. Switching to a new save should solve the issue
