### ISSUE TITLE
[FEATURE] Configure enemy resistances

### ISSUE THREAD

**Issue by ChloeIsNobody** [eternalUnion/UltraPain#18]
# Feature
I'm not sure how possible this is, but I would really like the ability to configure the types of damage that specific enemies are resistant or vulnerable to. It would be able to be configured within the enemy stat editor, and would include things like specific weapon damage, as well as damage types like explosions, falling, melee attacks, and maybe even hitscan attacks.

# Usage
This would allow a massive amount of additional customization options, and would allow for easier fine-tuning of difficulty and balancing of weapons to each player's preference. It would also allow players to set unique new ways to deal with enemies they find challenging, or to avoid relying on a specific method to take down an enemy.

**Comment by eternalUnion** [comment]
Yes, it is possible. Though it is stored as "weakness" in the game. And if the weakness multiplier is put below 100%, it becomes a resistance instead where 0% weakness = no damage from enemy. The only problem is that there are far too many damage categories. I cannot just make a field for every single damage type (which would trash the config) so the best implementation in my view would be to select the weakness from a dropdown list and enable/disable resistance that way. I will try to implement this tomorrow.

**Comment by eternalUnion** [comment]
Implemented first revision at https://github.com/eternalUnion/UltraPain/releases/tag/fr18-1.0.2-0. This version requires the development version of plugin configurator at https://github.com/eternalUnion/UKPluginConfigurator/releases/tag/dev-35f48b6
