### ISSUE TITLE
[FEATURE] Drone Sentry beam cooldown option in Enemy Tweaks

### ISSUE THREAD

**Issue by Megga1** [eternalUnion/UltraPain#22]
# Feature
Make a drone option for the sentry beam have a cooldown before shooting

# Usage
Imagine you are killing other enemies and you die because a drone shot you with a sentry beam and you couldn't hear it.
If the drones had an option for sentry beam cooldown it would be very helpful and useful

**Comment by eternalUnion** [comment]
This feature can be implemented with #12. Instead of cooldown, 2 features might be more appropriate:
* Chance of each attack
* Charge delay of each attack

**Comment by eternalUnion** [comment]
Implemented first revision of this feature at https://github.com/eternalUnion/UltraPain/releases/tag/fr12-1.0.2-1. There is a field for attack chance and attack delay (time between attack indication and shooting)
