### ISSUE TITLE
[BUG] performing a chargeback with a lightning attack spawned by a virtue doesn't instakill the virtue

### ISSUE THREAD

**Issue by mantacid** [eternalUnion/UltraPain#25]
# Description
Performing a chargeback on the enemy that made the attack always instakills them. virtues do not exhibit this behavior, even though they have a weakness to electric damage.

# Reproduction
Describe steps to reproduce the issue. If the way of reproducing the issue is unknown, you can include as much information as possible on when it happens or how often it happens
1. configure the virtue's attacks to be lightning bolts.
2. throw coins, attempting to chargeback the lightning.

Expected Result:
the lightning would be directed at the virtue, instakilling them like all other chargebacks in the game do.

Observed Result:
The virtue takes roughly two chargebacks to kill.

# Console logs
nothing abnormal was in the console logs.

**Comment by eternalUnion** [comment]
Yeah, it doesn't technically supposed to instakill on chargeback but it may need to logic wise. I will see what I can do

**Comment by EvolutioLunky** [comment]
I preformed this and it instant-killed it even though the damage multiplier of the lightning was 0.5.

https://github.com/eternalUnion/UltraPain/assets/112786974/5ba4df1a-e09a-4a1e-a39b-f37816d2035d

**Comment by eternalUnion** [comment]
Will close this issue as chargebacks don't have to instakill an enemy, and it would be hard to increase damage for a specific target for the chargeback
