### ISSUE TITLE
[FEATURE] Configurable Cooldowns

### ISSUE THREAD

**Issue by Holawenasx2** [eternalUnion/UltraPain#26]
[Please do not close the request after a revision release is posted. Request will be closed by the developer when it is implemented to the base version or when it is flagged as not planned]

# Feature
Probably one of the hardest things to implements, the feature would be able to configure the cooldowns of various weapons (marksman) 

# Usage
You could make the game even easier or harder, making marksman coins instant or making them really valuable, Railcannon charges quick or it needs more time to charge, it would be hell but probably a fun one
# Extras
nothing i guess

**Comment by eternalUnion** [comment]
I guess you mean weapon abilities by cooldown (not the fire rate) so I will make an editor for that which will include:
* Charged revolver regeneration speed
* Coin regeneration speed
* Sharpshooter regeneration speed
* Nail/saw regeneration speed
* Railgun regeneration speed
* Rocket freeze timer regeneration speed
* Cannonball regeneration speed
* EDIT: Also dash regeneration speed

**Comment by eternalUnion** [comment]
First revision https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-0
