### ISSUE TITLE
[FEATURE] Panopticon modifications

### ISSUE THREAD

**Issue by Skitter1200** [eternalUnion/UltraPain#28]
[Please do not close the request after a revision release is posted. Request will be closed by the developer when it is implemented to the base version or when it is flagged as not planned]

# Feature
Flesh Panopticon has the potential to absolutely **_body_** people if it just had a full fight. It would be quite the nasty surprise if you expected Sisyphus to deal with Panopticon for you and then nothing happens.

# Usage
In P-2, Sisyphus will sit back and let Panopticon bully you rather than making your life easier by breaking free. Sisyphus won't RIP AND TEAR his way out of the Panopticon until you actually deal the killing blow. 

# Extras
**m o r e  m e m e s**

**Comment by eternalUnion** [comment]
This is already planned to be implemented. It may require a little bit higher time limit for p2 though so may also need to make a level time limit editor

**Comment by eternalUnion** [comment]
Since we are doing a full fight, will also implement more panopticon attacks here to avoid merge conflicts
* Panopticon now spawns 3-axis beams
* During mortar attack, panopticon can spawn a spinning insignia attack like the first flesh prison

**Comment by eternalUnion** [comment]
First build https://github.com/eternalUnion/UltraPain/releases/tag/fr28-1.0.2-0
Next feature: DESTROY projectile during blackhole spawn

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr28-1.0.2-1 this release contains projectile on black hole spawn

Apart from that, I feel like config needs to be a little bit nerfed. It has been suggested that player should be pulled towards the eyes when hooked with whiplash

Next feature will be to add the level rank timing editor. This feature will likely require the development version of the plugin configurator

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr28-1.0.2-2
Had to implement a really quick feature to spawn golden eyes because several people suggested that it was harder to dodge attacks without golden eyes

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr28-1.0.2-4
Blue orb attack during mortar attack
Needs to be balanced
