### ISSUE TITLE
[FEATURE] Radiant Stalkers spread radiance

### ISSUE THREAD

**Issue by Skitter1200** [eternalUnion/UltraPain#29]
[Please do not close the request after a revision release is posted. Request will be closed by the developer when it is implemented to the base version or when it is flagged as not planned]

# Feature
In Patch 13b, Hakita made it so that radiant stalkers won't also give radiance to enemies they sand. As a pain enthusiast, I was disappointed by that change, to say the least.

# Usage
Whenever a radiant Stalker uses POCKET SAND, it will apply it's radiance to any of it's buddies it hits. If an enemy already has Radiance, then it will keep the highest radiance buff of each type. For example, a radiant Stalker with 2 stat points into HP sands an enemy with 1 point in HP and 1 in Speed, the enemy will have 2 points in HP and 1 in Speed.

# Extras
Oh, and not only will they survive if the option is turned on, they can also turn OTHER stalkers radiant, because fuck you.

**Comment by eternalUnion** [comment]
Sounds like a good idea

**Comment by UntotenTheo** [comment]
This would be awesome

**Comment by Skitter1200** [comment]
i see we are on the same wavelength of pain

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr29-1.0.2-0
