### ISSUE TITLE
[FEATURE] Minos prime phase modifications

### ISSUE THREAD

**Issue by eternalUnion** [eternalUnion/UltraPain#30]
# Feature
* First phase: Minos has no stamina meter like the second phase
* Second phase: Minos can combo attacks back to back
  * Can also throw projectile before (cannot teleport) and after (can teleport) judgement
  * Can instantly upswing after thy end is now's last attack
* Additional attacks
  * An attack like sisyphus' "This will hurt" explosion using the minos death animation and a blue explosion
  * Finishing off the 4 combo move with an explosion followed by an upswing
  * Random chance of throwing a projectile in the middle of combos before continuing

# Usage
Making minos generally harder. Should also buff the default stats

**Comment by UntotenTheo** [comment]
PHASE 2 START LETS GO

Suggestion: What if Minos Prime had a chance to throw a serpent for every punch he threw?

Slightly Evil Suggestion: What if Minos Primes voicelines (and subtitles) were delayed for his attacks, that way he basically announces what move he performs _**as**_ he's doing them, just like Sisyphus Prime.

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr30-1.0.2-0
Needs more testing, maybe speed can be increased

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr30-1.0.2-1
Speed could still be increased
