### ISSUE TITLE
[FEATURE] interaction with explosives for the screwdriver

### ISSUE THREAD

**Issue by EvolutioLunky** [eternalUnion/UltraPain#34]
# Feature
Allowing the screwdriver to get launched by explosions, turning it into a hit-scan auto aim piercing projectile that shreds enemies. giving the +HeavenPierceHer style messege.

# Usage
Style and damage.

# Extras
it would have a similar auto aim order of operations to coins.

if it hits a coin it will split the hit-scan into 2 beams with half the damage.

the piercing is based on the enemies health. less health makes it drill through them. more health makes it take a second or two to go through dealing more damage, effectively making it do percentage based damage.

**Comment by UntotenTheo** [comment]
I don't see this being useful im ngl, screwdriver would be difficult to launch using explosives, KB being an exception.

If you want an auto aim hitscan attack that pierces and 'shreds enemies', may I direct you to the Coin + Slab Piercer/Any Sharpshooter Combo?

**Comment by eternalUnion** [comment]
More useful feature could be to being able to parry screwdriver on launch, making it home toward a magneted enemy

**Comment by EvolutioLunky** [comment]
that works.

**Comment by eternalUnion** [comment]
A similar feature was implemented, making screwdriver split grenades with auto aim
