### ISSUE TITLE
[BUG] multiple screwdrivers can split a single target if the drill is in an enemy. 

### ISSUE THREAD

**Issue by EvolutioLunky** [eternalUnion/UltraPain#35]
# Description
multiple screwdrivers can split a single target if the drill is in an enemy. 

https://github.com/eternalUnion/UltraPain/assets/112786974/a5b4c88b-ab43-42d6-b99a-5325ff6e8fb3

**Comment by eternalUnion** [comment]
![image](https://github.com/eternalUnion/UltraPain/assets/30156046/59cb610f-d91a-434c-9014-84a5bbe01017)
I tested it and it seems correct amount of coins are created but they overlap, creating the illusion of them being split only once

**Comment by eternalUnion** [comment]
This issue will be closed due to multiple screwdrivers already splitting coins correctly. For a visual enchantment, comment on #3
