### ISSUE TITLE
In the enemy stat editor, Sentries are called 'Turret'

### ISSUE THREAD

**Issue by TheTurd125** [eternalUnion/UltraPain#37]
![bruh1](https://github.com/eternalUnion/UltraPain/assets/79824410/8c38a7d5-4c9f-4ce3-848c-14414c335943)
![bruh2](https://github.com/eternalUnion/UltraPain/assets/79824410/f8db0598-bd85-454a-9042-36e7568a4f75)

**Comment by eternalUnion** [comment]
Fixed on development branch with [c02fe90](https://github.com/eternalUnion/UltraPain/commit/c02fe90f68a45a9f2b47c736ea5e3a4a347b6482)
