### ISSUE TITLE
Kamikaze Homing Drones

### ISSUE THREAD

**Issue by Holawenasx2** [eternalUnion/UltraPain#4]
# Feature
When drones die and try to Kamikaze you, instead of going in an straight line, the Drone will chase you.

# Usage
It would impact the game in an extreme way, as you have to or blow up the dead drones or inflict enough damage to them so they explode instantly, you can still parry the drones and of course, use the KB to repel them.
# Extras
Nothing Extra

**Comment by eternalUnion** [comment]
Implemented first revision at https://github.com/eternalUnion/UltraPain/releases/tag/fr4-1.0.2-0. Sorry for the delay, lot of requests recently

**Comment by Holawenasx2** [comment]
Cool, i understand and thanks

**Comment by Holawenasx2** [comment]
sorry i closed it 3 days ago
