### ISSUE TITLE
[FEATURE] Whiplash hard damage cap

### ISSUE THREAD

**Issue by Skitter1200** [eternalUnion/UltraPain#42]
[Please do not close the request after a revision release is posted. Request will be closed by the developer when it is implemented to the base version or when it is flagged as not planned]

# Feature
After the big Whiplash nerf, it was changed to cap out at a maximum of 50 hard damage instead of being able to go as far down as your missing HP. That's not painful enough for my liking.

# Usage
When using the Whiplash while missing HP, it will continue to build hard damage past 50.

# Extras
more memes

**Comment by eternalUnion** [comment]
This feature will be implemented along #36 as hard damage is partially modified there. Hard damage buildup speed and cap will be configurable

**Comment by eternalUnion** [comment]
This build contains whiplash hard damage editor as well as the player stat editor https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-2
