### ISSUE TITLE
[FEATURE] Minos' combos

### ISSUE THREAD

**Issue by Brishenn** [eternalUnion/UltraPain#43]
# Feature
The Ferryman has a config where his combos can be extended. In a similar fashion, is it possible to alter Minos's combos, or extend them? (Ex. he yells "Thy end is now!" but instead shoots a snake at the end rather than slamming the ground.)

# Usage
This could mix up his gameplay and force a player to get used to new combos they propose on themselves.

# Extras
Maybe a possibility for custom combos in his second phase on Violent+? (ex. Judgement with "Prepare thyself" start up, followed by the first two hits of Prepare thyself, and so on.) Specifically Violent+ incase his stamina gets in the way of this.

**Comment by eternalUnion** [comment]
Minos modifications are made on #30. Similar features had already been implemented there. I will also upload a new build with better minos teleportation trail with transparency and stuff. If you have any suggestion for minos comment them there
