### ISSUE TITLE
[BUG] Object reference not set to an instance of the object

### ISSUE THREAD

**Issue by BlaixenU** [eternalUnion/UltraPain#44]
# Description
Playing normally and fighting swordsmachines creates this error spam. Most notable issue is that, on lower end devices at least, your ingame sensitivity feels slower because of the error spam (i think). Happened in both P-2 and the Cybergrind

# Reproduction

* Step 1:  kill a swordsmachine
* Step 2: check bepinex console

# Console logs
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Ultrapain.Patches.SwordsMachineFlag.Update () (at <d5500e16cc764fd5817bd942ad7ba1db>:0)

# Extras

![image](https://github.com/eternalUnion/UltraPain/assets/47916471/d69653bb-ce45-40e1-a71d-68869bf2189a)

**Comment by eternalUnion** [comment]
Thought fixed this bug but there it is again. I will fix it but could you tell me the version of the plugin you are using just in case?

**Comment by eternalUnion** [comment]
From what I see a temporary solution would be to not use speed up phase for swordsmachine

**Comment by eternalUnion** [comment]
I could not reproduce this bug on 1.0.2, please make sure you have the latest version of the plugin. If the plugin is already on 1.0.2, I will make a fix.

**Comment by BlaixenU** [comment]
> Thought fixed this bug but there it is again. I will fix it but could you tell me the version of the plugin you are using just in case?

I play through r2modman and make sure to update my mods as I get on, and I have checked and am playing on 1.0.2.

**Comment by BlaixenU** [comment]
> I could not reproduce this bug on 1.0.2, please make sure you have the latest version of the plugin. If the plugin is already on 1.0.2, I will make a fix.

It's random from my experience. If necessary, I can provide my system specifications.

**Comment by eternalUnion** [comment]
No need, it happened randomly on my side too so I will release a fix

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/1.0.3
Should be fixed on 1.0.3. The problem was solved but was not implemented to 1.0.2. Since I was using the development version I could not reproduce it before.

**Comment by BlaixenU** [comment]
reminder that this still happens in the new version
