### ISSUE TITLE
[FEATURE] 5-2 possible level changes

### ISSUE THREAD

**Issue by JustWantAName06** [eternalUnion/UltraPain#49]
# Feature
On the level 5-2 add waves than rise above the platforms. each do 15 damage on default and are at half jump height from the first rock part (1 schism, 2 drones, 1 sentry)
# Usage
Makes the level harder (?) and cannot affect enemies
# Extras
A way to change wave speed, wave height and wave damage

**Comment by UntotenTheo** [comment]
This is an interesting idea but I'm not sure if it can be implemented.

If added, I believe this would fit in to 5-4 as well.

**Comment by eternalUnion** [comment]
Kinda hard to implement since water waves are not in the game

**Comment by eternalUnion** [comment]
Will not implement, the feature is too specific and editing all levels to make it more general would take too much development time
