### ISSUE TITLE
[BUG] Getting stuck after level completion

### ISSUE THREAD

**Issue by blueperson2** [eternalUnion/UltraPain#58]
# Description
Upon completing a level, V1 will endlessly fall through the terminal. The element of the end-screen scoring to show points gained (TOTAL: +0P) will appear, but not go up at all. Tab can be held to show the time/kills/style, and the timer is stopped. The game can be paused and the level can be exited, and will count as completed in the menus, but no rank is given.

# Reproduction
In the bepinex plugins folder, have pluginconfigurator.dll, Ultrapain.dll, and the seemingly extension-less file just named "ultrapain"
I have moved my UMM folder outside of plugins and into the bepinex folder itself to disable it, and that did not fix it. Deleting UMM entirely also didn't fix it. Other mods don't seem to have an effect.
Click play, select Ultrapain, and play any level to completion. The bug occurs upon entering the exit terminal.

# Plugin versions
* UltraPain - 1.0.3
* PluginConfigurator - 1.5.3

# Console logs

These happen on startup
[Error  : Unity Log] Unable to open archive file: D:/Program Files (x86)/Steam/steamapps/common/ULTRAKILL/BepInEx/plugins/pluginconfigurator
[Error  : Unity Log] Failed to read data for the AssetBundle 'D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\pluginconfigurator'.

These happen upon level completion
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
RankData..ctor (StatsManager sman) (at <b6df9e1eeb254e1a84fb5ecc699b7f07>:0)
GameProgressSaver.SaveRank () (at <b6df9e1eeb254e1a84fb5ecc699b7f07>:0)
StatsManager.SendInfo () (at <b6df9e1eeb254e1a84fb5ecc699b7f07>:0)
FinalPit.SendInfo () (at <b6df9e1eeb254e1a84fb5ecc699b7f07>:0)
FinalPit.OnTriggerStay (UnityEngine.Collider other) (at <b6df9e1eeb254e1a84fb5ecc699b7f07>:0)

# Extras
Everything else about the mod works fine, including modifying it through plugin config, despite the error logs. Plugin configurator also works with everything else it can change, like the level loader. The issue only happens when playing Ultrapain difficulty on any level, vanilla or not.

Not too long ago, my boot drive got many of the files related to startup heavily corrupted, and nothing more. I don't know the exact details because of the nature of it. Ultrakill was also on this drive. I wiped the other drive and made that my boot drive. Occasionally, applications will be inaccessible from the former boot drive, typically ones that messed with emulation of some kind (like vmbox or dolphin emu). I don't think this has anything to do with the Ultrapain problem, as everything on Steam worked fine, and I am only modding the game well after this incident. Still worth mentioning though.

**Comment by eternalUnion** [comment]
The first issue I see is plugin configurator missing its asset file. Plugin configurator comes with an extensionless file which contains the assets for its sprites and some other stuff. You will want to put configurator under BepInEx/PluginConfigurator/<files>. This should not be the issue causing the bug though

You could try playing ukmd from the game trough the console

You could also try creating a new save. This is a theory, but if you have been playing on the same save which was created from a very early version of the game, ukmd slot could have not been allocated in the save file.

If that doesn't work as well, you could try redownloading the plugins (make sure they have their own dedicated folders inside plugins as well as their assets right beside them though I could not recreate the issue trough wrong placement of files) and maybe by validating game files

What you can try temporarely: For now, enabling global difficulty and playing on violent. This will only affect base difficulty (not being ukmd)

**Comment by blueperson2** [comment]
Changing save files fixed the issue. Thank you.
