### ISSUE TITLE
FEATURE] Mod Attack only option for things like the Drone

### ISSUE THREAD

**Issue by Madeline69a** [eternalUnion/UltraPain#6]
# Feature
1. to practice the aiming for the attack
2. to have all drones shoot you dead at once with sentryshot

# Usage
Chargebacks

# Extras
i want to make a montage with this so badly

**Comment by eternalUnion** [comment]
This feature will be implemented soon with #12

**Comment by eternalUnion** [comment]
Will now be done under #22 since the point is similar and splitting the feature into 2 makes it hard to merge later. Drones will also have an orbital strike interaction with #15.

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr12-1.0.2-1 contains ability to disable projectiles for drones, which achieves the point of this request
