### ISSUE TITLE
A new feature for Something Wicked

### ISSUE THREAD

**Issue by Brishenn** [eternalUnion/UltraPain#7]
# Feature
Lets have him the ability to shoot a Hideous Mass hook?

# Usage
Since he's only in one level in the entire game, why not make him shoot something that majorly slows you down when it hits?

# Extras
And if at all possible, maybe he can spawn in 4-3 after the supposed fake-out?

**Comment by Skitter1200** [comment]
Seconded. This sounds like some good pain.

**Comment by eternalUnion** [comment]
First revision released at https://github.com/eternalUnion/UltraPain/releases/tag/fr7-1.0.2-0

**Comment by Brishenn** [comment]
Can confirm that this has made the chases much more intense if you try to jump to get away.
