### ISSUE TITLE
(probably unfixable) [BUG] Stalkers will still survive explosion even if the 'Survive Explosion' setting is off

### ISSUE THREAD

**Issue by UntotenTheo** [eternalUnion/UltraPain#78]
obviously only occurs if playing the difficulty via the UKMD slot
unsure if its possible to override

**Comment by eternalUnion** [comment]
Yeah it is, will implement along #77 later on

**Comment by UntotenTheo** [comment]
![Screenshot_16](https://github.com/eternalUnion/UltraPain/assets/75056493/91878b0c-0f8e-40aa-9c9b-b6a9a380884f)
gotcha, closing issue
