### ISSUE TITLE
Config Profiles

### ISSUE THREAD

**Issue by EvolutioLunky** [eternalUnion/UltraPain#79]
# Feature
Just requesting a way to save different versions of the config so you can easily switch between them.

# Usage
It is primarily a QoL request but I think its a fair one.

**Comment by eternalUnion** [comment]
Plugin configurator presets already exist
![image](https://github.com/eternalUnion/UltraPain/assets/30156046/fc8ea14a-dc0a-4d58-9fe9-c4f18dac3334)

**Comment by EvolutioLunky** [comment]
oops
