### ISSUE TITLE
[FEATURE] Idol idea

### ISSUE THREAD

**Issue by Brishenn** [eternalUnion/UltraPain#9]
# Explode when destroyed
Not sure how hard it would be to do this... but perhaps Idols release an explosion when broken? The kind that damages you?

# Usage
Well, filths turn into creepers, so why not make the Idol's harmless explosion, harmful?

# Extras
None

**Comment by eternalUnion** [comment]
Released on https://github.com/eternalUnion/UltraPain/releases/tag/fr9-1.0.1-0. Needs more testing before implemented.

**Comment by Brishenn** [comment]
Tested it out in 5-2 and Cybergrind, all the explosions seem to work well. Recommend that it doesn't do friendly fire though, the filth that showed off the first Idol in 5-2 was killed by the explosion.

**Comment by eternalUnion** [comment]
A slider for enemy damage percent will be included in the second revision

**Comment by eternalUnion** [comment]
Second revision released at https://github.com/eternalUnion/UltraPain/releases/tag/fr9-1.0.1-1
